// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoOtm_lYItoNCM-9sNjjnwX4DdW_sHqiI',
    appId: '1:636065186155:web:cfdc9bf51293b3aa61cc2e',
    messagingSenderId: '636065186155',
    projectId: 'hbttrckr-b580a',
    authDomain: 'hbttrckr-b580a.firebaseapp.com',
    storageBucket: 'hbttrckr-b580a.firebasestorage.app',
    measurementId: 'G-WZWEZ39Z3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0Kosrg29NsQbRjXNntfRs9niui37fdE',
    appId: '1:636065186155:android:63234ceeeb3513bd61cc2e',
    messagingSenderId: '636065186155',
    projectId: 'hbttrckr-b580a',
    storageBucket: 'hbttrckr-b580a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SAzbQBFNSxtsm0V4DSELkoiR52WqeVk',
    appId: '1:636065186155:ios:2e3ff6c829212ebe61cc2e',
    messagingSenderId: '636065186155',
    projectId: 'hbttrckr-b580a',
    storageBucket: 'hbttrckr-b580a.firebasestorage.app',
    iosBundleId: 'com.example.hbttrckr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SAzbQBFNSxtsm0V4DSELkoiR52WqeVk',
    appId: '1:636065186155:ios:2e3ff6c829212ebe61cc2e',
    messagingSenderId: '636065186155',
    projectId: 'hbttrckr-b580a',
    storageBucket: 'hbttrckr-b580a.firebasestorage.app',
    iosBundleId: 'com.example.hbttrckr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoOtm_lYItoNCM-9sNjjnwX4DdW_sHqiI',
    appId: '1:636065186155:web:e405ddc019179aee61cc2e',
    messagingSenderId: '636065186155',
    projectId: 'hbttrckr-b580a',
    authDomain: 'hbttrckr-b580a.firebaseapp.com',
    storageBucket: 'hbttrckr-b580a.firebasestorage.app',
    measurementId: 'G-KR075CLN3Z',
  );
}
